# Generated by Django 4.0.2 on 2022-02-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulant',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Undefined')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Enviada'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='SUBMITTED', max_length=50, verbose_name='Status'),
        ),
    ]
